In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display

#%matplotlib notebook

import sklearn
import matplotlib as mpl
import seaborn as sns

import re

%matplotlib inline

pd.options.display.max_rows = 10

In [2]:
# Dataset

# use this if in fmi-hw... repo
# train = pd.read_csv("data/spooky/train.zip", index_col=['id'])
# test = pd.read_csv("data/spooky/test.zip", index_col=['id'])
# sample_submission = pd.read_csv("data/spooky/sample_submission.zip", index_col=['id'])

train = pd.read_csv("data/train.zip", index_col=['id'])
test = pd.read_csv("data/test.zip", index_col=['id'])
sample_submission = pd.read_csv("data/sample_submission.zip", index_col=['id'])


print(train.shape, test.shape, sample_submission.shape)
print(set(train.columns) - set(test.columns))

(19579, 2) (8392, 1) (8392, 3)
{'author'}


In [3]:
train.head(5)

text author
id                                                               
id26305  This process, however, afforded me no means of...    EAP
id17569  It never once occurred to me that the fumbling...    HPL
id11008  In his left hand was a gold snuff box, from wh...    EAP
id27763  How lovely is spring As we looked from Windsor...    MWS
id12958  Finding nothing else, not even gold, the Super...    HPL

# Идеи за фичъри:
    
* ~~CountVectorizer, Tfidf~~
* ~~Preprocessing - stop words, lematization~~
* ~~Други фичъри - бр. думи , бр. стоп думи, бр. пунктуация, бр. ГЛАВНИ букви и т.н.~~
* Намиране на общи теми чрез LDA
* Word Embeddings с невронни мрежи


# Първо - baseline модел

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score

In [5]:
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', LinearSVC())
])

cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3)

array([ 0.78783701,  0.79635305,  0.79509579])

Да пробваме с RF

In [6]:
from sklearn.ensemble import RandomForestClassifier
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', RandomForestClassifier())
])

# print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[ 0.62300858  0.61798958  0.60551724]

[-1.36418837 -1.38716468 -1.43783028]

In [7]:
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', LogisticRegression())
])

# print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))
# print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3, 
#                       scoring='neg_log_loss'))

# Получихме малко по-добри резултати

[ 0.81449142  0.81673307  0.81348659]

[-0.47678328 -0.47558895 -0.47131481]

Следващото е за да имаме "explore" датасет

In [8]:
explore = train.copy()

In [9]:
import nltk
# nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')

In [10]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

stem = PorterStemmer()

explore['stemmed'] = explore.text.apply(lambda t: " ".join([stem.stem(w) for w in t.split()])) 

explore[['stemmed', 'text']].head()

stemmed  \
id                                                           
id26305  thi process, however, afford me no mean of asc...   
id17569  It never onc occur to me that the fumbl might ...   
id11008  In hi left hand wa a gold snuff box, from whic...   
id27763  how love is spring As we look from windsor ter...   
id12958  find noth else, not even gold, the superintend...   

                                                      text  
id                                                          
id26305  This process, however, afforded me no means of...  
id17569  It never once occurred to me that the fumbling...  
id11008  In his left hand was a gold snuff box, from wh...  
id27763  How lovely is spring As we looked from Windsor...  
id12958  Finding nothing else, not even gold, the Super...

# Допълнителните фичъри не сработиха, стеминга също. 

Остават да пробвам:

* ~~Оптимизиране на модела с CountVectorizer.~~
* Добавяне на още фичъри, от латентни пространства (LDA) - topic modeling.
* Word embeddings с невронни мрежи.
* Стакинг на класификатори.

За сега ще разгледаме само оптимизирането на модела.

Първо да опишем параметрите за търсене в трансфомацията (CountVectorizer)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

params_count_word = {"features__ngram_range": [(1,1), (1,2), (1,3)],
                      "features__analyzer": ['word'],
                      "features__max_df":[1.0, 0.9, 0.8, 0.7, 0.6, 0.5],
                      "features__min_df":[2, 3, 5, 10],
                      "features__lowercase": [False, True],
                      "features__stop_words": [None, stopwords]}

params_count_char = {"features__ngram_range": [(1,4), (1,5), (1,6)],
                      "features__analyzer": ['char'],
                      "features__max_df":[1.0, 0.9, 0.8, 0.7, 0.6, 0.5],
                      "features__min_df":[2, 3, 5, 10],
                      "features__lowercase": [False, True],
                      "features__stop_words": [None, stopwords]}

In [12]:
def report(results, n_top=5):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")


In [13]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import log_loss
from sklearn.naive_bayes import MultinomialNB

In [14]:
def random_search():
    params = {
        "clf__alpha": [0.001, 0.005, 0.01, 0.05, 0.1, 0.3]
    }

    params.update(params_count_word)

    pipeline = Pipeline([
        ('features', TfidfVectorizer()),
        ('clf', MultinomialNB())
    ])

    random_search = RandomizedSearchCV(pipeline, param_distributions=params, 
                                       scoring='neg_log_loss',
                                       n_iter=20, cv=3, n_jobs=4)

    random_search.fit(explore.stemmed, train.author)
    report(random_search.cv_results_)
    
# random_search()  # -0.423

Model with rank: 1
Mean validation score: -0.438 (std: 0.002)
Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 2), 'features__min_df': 2, 'features__max_df': 0.6, 'features__lowercase': False, 'features__analyzer': 'word', 'clf__alpha': 0.01}

Model with rank: 2
Mean validation score: -0.443 (std: 0.004)
Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 3), 'features__min_df': 3, 'features__max_df': 0.6, 'features__lowercase': True, 'features__analyzer': 'word', 'clf__alpha': 0.05}

Model with rank: 3
Mean validation score: -0.453 (std: 0.002)
Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 3), 'features__min_df': 2, 'features__max_df': 1.0, 'features__lowercase': False, 'features__analyzer': 'word', 'clf__alpha': 0.01}

Model with rank: 4
Mean validation score: -0.471 (std: 0.003)
Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 2), 'features__min_df': 5, 'features__max_df': 1.0, 'features__lowercase': False, 'features__analyzer': 'word', 'clf__alpha': 0.01}

Model with rank: 5
Mean validation score: -0.472 (std: 0.004)
Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 3), 'features__min_df': 5, 'features__max_df': 0.5, 'features__lowercase': False, 'features__analyzer': 'word', 'clf__alpha': 0.05}


In [15]:
# import keras
# from keras.datasets import mnist
# from keras.models import Sequential
# from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, Dropout, Lambda, Concatenate
# from keras.optimizers import RMSprop, Adam
# from keras import regularizers, objectives, metrics
# from keras.models import Model
# from keras import backend as K

# from IPython.display import display

In [16]:
from gensim import corpora

documents = train.text

In [17]:
# # remove common words and tokenize
# # stoplist = set('for a of the and to in'.split())
# texts = [[word for word in document.lower().split() if word not in stopwords] #was stoplist
#          for document in documents]

# # remove words that appear only once
# from collections import defaultdict
# frequency = defaultdict(int)
# for text in texts:
#     for token in text:
#         frequency[token] += 1

# texts = [[token for token in text if frequency[token] > 1] for text in texts]

# from pprint import pprint  # pretty-printer
# pprint(texts[:2])

In [18]:
import pickle
from pathlib import Path
from pprint import pprint  # pretty-printer

TOKENIZED_FILENAME = "processed_texts.pickle"

try:
    # depicke
    texts = pickle.load(open(TOKENIZED_FILENAME, "rb"))   
except FileNotFoundError:
    # remove common words and tokenize
    # stoplist = set('for a of the and to in'.split())
    texts = [[word for word in document.lower().split() if word not in stopwords] #was stoplist
             for document in documents]

    # remove words that appear only once
    from collections import defaultdict
    frequency = defaultdict(int)
    for text in texts:
        for token in text:
            frequency[token] += 1

    texts = [[token for token in text if frequency[token] > 1] for text in texts]

    from pprint import pprint  # pretty-printer
    
    # create pickle
    pickle.dump(texts, open(TOKENIZED_FILENAME, "wb" ))

pprint(texts[:2])    

[['process,',
  'however,',
  'afforded',
  'means',
  'ascertaining',
  'dimensions',
  'might',
  'make',
  'return',
  'point',
  'whence',
  'set',
  'out,',
  'without',
  'aware',
  'perfectly',
  'uniform',
  'seemed',
  'wall.'],
 ['never', 'occurred', 'fumbling', 'might', 'mere', 'mistake.']]


In [19]:
DICT_FILENAME = 'spooky.dict'

try:
    dictionary = corpora.Dictionary.load(DICT_FILENAME)
except FileNotFoundError:
    dictionary = corpora.Dictionary(texts)
    dictionary.save(DICT_FILENAME)  # store the dictionary, for future reference

print(len(dictionary))

22328


In [20]:
CORPUS_FILENAME = 'spooky.mm'

try:
    #restore from disk
    corpus = corpora.mmcorpus.MmCorpus(CORPUS_FILENAME)
except FileNotFoundError:
    corpus = [dictionary.doc2bow(text) for text in texts]
    corpora.MmCorpus.serialize('spooky.mm', corpus)  # store to disk, for later use

print(corpus[156])

[(545, 1.0), (1137, 1.0), (1598, 1.0), (1599, 1.0), (1600, 1.0), (1601, 1.0)]


In [21]:
print('in df:     ', train.text[0],'\n')
print('as doc:    ', documents[0],'\n')
print('as tokens: ', texts[0],'\n')
print('as vec:    ', corpus[0],'\n')

in df:      This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall. 

as doc:     This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall. 

as tokens:  ['process,', 'however,', 'afforded', 'means', 'ascertaining', 'dimensions', 'might', 'make', 'return', 'point', 'whence', 'set', 'out,', 'without', 'aware', 'perfectly', 'uniform', 'seemed', 'wall.'] 

as vec:     [(0, 1.0), (1, 1.0), (2, 1.0), (3, 1.0), (4, 1.0), (5, 1.0), (6, 1.0), (7, 1.0), (8, 1.0), (9, 1.0), (10, 1.0), (11, 1.0), (12, 1.0), (13, 1.0), (14, 1.0), (15, 1.0), (16, 1.0), (17, 1.0), (18, 1.0)] 



## similarities.docsim.Similarity

In [22]:
from gensim import similarities

index = similarities.docsim.Similarity('/home/bob/tmp', corpus, num_features=len(dictionary)) 
sims = index[corpus[0]]

In [23]:
from operator import itemgetter

results = list(enumerate(sims))
top = sorted(results, key=itemgetter(1), reverse=True)
top[:5]

[(0, 0.99999982),
 (14771, 0.260133),
 (8578, 0.22941573),
 (12208, 0.22941573),
 (12524, 0.22941573)]

In [24]:
print('Comparing to document: ', documents[0], '\n\n')
for sim in top[:10]:
    print(sim[1], '|', train.author[sim[0]], '|', documents[sim[0]],'\n')

Comparing to document:  This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall. 


1.0 | EAP | This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall. 

0.260133 | EAP | The expression of his smile, however, was by no means unpleasing, as might be supposed; but it had no variation whatever. 

0.229416 | EAP | Much, however, might be ascertained. 

0.229416 | EAP | I reapproached the wall. 

0.229416 | HPL | They seemed to hate and fear him at the same time, and he seemed to return these sentiments. 

0.229416 | EAP | There was nothing in this, however, to make him sob. 

0.216295 | EAP | At first he stared at me as if he found it impossible

Чисто технически може да се направи някакво осредняване на резултати - например резултатите от сравнение към documents[0] и сравнение към documents[2] - като и двата записа са "EAP". Но не ми се вижда правилно.

Не мисля, че посоката е подходяща за нашия случай, защото сравненията са директни, вместо да се извлича "пространство" което да генерализира стила/автора. По-добре да проверим какво друго има в gensim.

In [25]:
from gensim import sklearn_api

from sklearn.ensemble import RandomForestClassifier
pipeline = Pipeline([
    ('features', sklearn_api.text2bow.Text2BowTransformer()),
    ('clf', RandomForestClassifier())
])

try:
    print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))
    print(cross_val_score(pipeline, train.text, train.author, 
                    cv=3, n_jobs=3, scoring='neg_log_loss'))
except ValueError as e:
#     print(e)
    pass

ValueError: setting an array element with a sequence.

In [26]:
something = sklearn_api.text2bow.Text2BowTransformer()
print(type(something))
other = something.fit_transform(train.text)
print(type(other))
print(train.text[0], other[0], '\n', train.text[656], other[656])

<class 'gensim.sklearn_api.text2bow.Text2BowTransformer'>
<class 'list'>
This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall. [(0, 2), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 3), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 4), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1)] 
 Dropping of its own accord upon his exit or perhaps purposely closed, it had become fastened by the spring; and it was the retention of this spring which had been mistaken by the police for that of the nail, farther inquiry being thus considered unnecessary. [(3, 1), (7, 1), (13, 1), (20, 3), (29, 4), (44, 1), (60, 1), (70, 1), (71, 1), (78, 2), (95, 2), (133, 1), (143, 2), (174, 1), 

How is this supposed to work?!?

`tfidf.fit_transform(corpus)` returns matrix, while the `sklearn_api.text2bow.Text2BowTransformer().fit_transform(corpus)` returns some "BOW" format

OK - this might work

In [27]:
pipeline = Pipeline([
    ('features', sklearn_api.text2bow.Text2BowTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer()),
    ('clf', RandomForestClassifier())
])

# print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[ 0.48360907  0.48850751  0.48613027]<br>
[-2.1033608  -2.09791398 -2.30065565]

Преди да пообработим текста да видим Logistic Regression

In [28]:
pipeline = Pipeline([
    ('features', sklearn_api.text2bow.Text2BowTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer()),
    ('clf', LogisticRegression())
])


In [29]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))

[ 0.53722426  0.53463071  0.53563218]<br>
CPU times: user 430 ms, sys: 169 ms, total: 599 ms<br>
Wall time: 3min 41s

In [30]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-0.96678405 -0.97080789 -0.97363342]<br>
CPU times: user 453 ms, sys: 121 ms, total: 573 ms<br>
Wall time: 3min 39s

Още един опит преди да окастрим текста

In [31]:
pipeline = Pipeline([
    ('features', sklearn_api.text2bow.Text2BowTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer(num_topics=21)),
    ('clf', LogisticRegression())
])

In [32]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-0.98861154 -0.97565475 -0.99821168]<br>
CPU times: user 381 ms, sys: 99.9 ms, total: 481 ms<br>
Wall time: 2min 8s

In [33]:
explore.stemmed

id
id26305    thi process, however, afford me no mean of asc...
id17569    It never onc occur to me that the fumbl might ...
id11008    In hi left hand wa a gold snuff box, from whic...
id27763    how love is spring As we look from windsor ter...
id12958    find noth else, not even gold, the superintend...
                                 ...                        
id17718    I could have fancied, while I look at it, that...
id08973     the lid clench themselv togeth as if in a spasm.
id05267    mai il faut agir that is to say, a frenchman n...
id17513    for an item of news like this, it strike us it...
id00393    He laid a gnarl claw on my shoulder, and it se...
Name: stemmed, Length: 19579, dtype: object

In [34]:
from gensim.parsing.preprocessing import preprocess_string, strip_punctuation, remove_stopwords

# CUSTOM_FILTERS = [strip_punctuation, remove_stopwords]
# explore['stemmed2'] = [ preprocess_string(s, CUSTOM_FILTERS) for s in explore.stemmed]
# explore.stemmed2

explore['stemmed2'] = [ strip_punctuation(remove_stopwords(s.lower())) for s in explore.stemmed]
explore.stemmed2

id
id26305    thi process  however  afford mean ascertain di...
id17569                        onc occur fumbl mere mistake 
id11008    hi left hand wa gold snuff box  which  caper h...
id27763    love spring look windsor terrac sixteen fertil...
id12958    noth else  gold  superintend abandon hi attemp...
                                 ...                        
id17718    fancied  look it  emin landscap painter built ...
id08973                    lid clench themselv togeth spasm 
id05267      mai il faut agir say  frenchman faint outright 
id17513    item news like this  strike wa veri coolli rec...
id00393    laid gnarl claw shoulder  shake wa altogeth mi...
Name: stemmed2, Length: 19579, dtype: object

In [35]:
print(explore.loc['id17569'].stemmed, '|||', explore.loc['id17569'].stemmed2)

It never onc occur to me that the fumbl might be a mere mistake. ||| onc occur fumbl mere mistake 


Pipeline-a си е същия

In [36]:
# %%time
# print(cross_val_score(pipeline, explore.stemmed2, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-1.05550683 -1.02313271 -1.02899542]<br>
CPU times: user 347 ms, sys: 92.8 ms, total: 440 ms<br>
Wall time: 1min 27s

Поне е по-бързо. Да видим tfidf и повече фичъри.

In [37]:
pipeline = Pipeline([
    ('bow', sklearn_api.text2bow.Text2BowTransformer()),
    ('features', sklearn_api.tfidf.TfIdfTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer(num_topics=501)),
    ('clf', LogisticRegression())
])

In [38]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-0.94941507 -0.95248997 -0.95026712]<br>
CPU times: user 1.18 s, sys: 223 ms, total: 1.4 s<br>
Wall time: 19min 4s

This is frustrating

In [39]:
pipeline = Pipeline([
    ('bow', sklearn_api.text2bow.Text2BowTransformer()),
    ('features', sklearn_api.tfidf.TfIdfTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer()),
    ('clf', LogisticRegression())
])

In [40]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-1.03061917 -1.03984701 -1.03884094]<br>
CPU times: user 387 ms, sys: 124 ms, total: 511 ms<br>
Wall time: 2min 33s

In [41]:
pipeline = Pipeline([
    ('bow', sklearn_api.text2bow.Text2BowTransformer()),
    ('features', sklearn_api.tfidf.TfIdfTransformer()),
    ('lda', sklearn_api.ldamodel.LdaTransformer()),
    ('clf', MultinomialNB())
])

In [42]:
# %%time
# print(cross_val_score(pipeline, train.text, train.author, 
#                 cv=3, n_jobs=3, scoring='neg_log_loss'))

[-1.06731359 -1.07019065 -1.07019197]<br>
CPU times: user 377 ms, sys: 142 ms, total: 519 ms<br>
Wall time: 2min 29s

От къде е тая разлика? Може ли text2bow да чупи? Или е от липсата на хипер парамерти?

In [43]:
print(corpus)

MmCorpus(19579 documents, 22328 features, 240166 non-zero entries)


corpus е минат с word2vec; ще прескоча tfidf за момента и ще пусна LdaModel

In [44]:
from gensim.models.ldamodel import LdaModel

# lda = LdaModel(corpus=corpus, id2word=dictionary)
# lda.print_topic(0)

In [45]:
# id2word=dict([(i, s) for i, s in enumerate(dictionary)])
# print([ id2word[z] for z in range(10) ])
# print(list(id2word.items())[:10])
# what = list(enumerate(dictionary))
# print(what[:10])
# print(list(dictionary)[:10])
# print(type(dictionary))
# wdk = dictionary.keys()
# print(wdk[:10])
# print(dictionary[wdk[0]])

Горното даваше topic с референции към IDта вместо към реални думи - не знам защо сега работи

In [46]:
%%time
lda = LdaModel(corpus=corpus, id2word=dict(dictionary.items()))

/home/bob/.local/lib/python3.6/site-packages/gensim/models/ldamodel.py:802: RuntimeWarning: divide by zero encountered in log
  diff = np.log(self.expElogbeta)


CPU times: user 1min 15s, sys: 607 ms, total: 1min 15s
Wall time: 1min 15s


Представянето на topic:

In [47]:
lda.print_topic(0)

'0.068*"cannot" + 0.056*"true" + 0.054*"town" + 0.053*"best" + 0.042*"done" + 0.032*"says" + 0.029*"books" + 0.029*"wide" + 0.029*"friends" + 0.027*"imagine"'

In [48]:
lda.show_topics(num_topics=10, num_words=10)

[(9,
  '0.087*"dreams" + 0.040*"find" + 0.036*"bodies" + 0.031*"noticed" + 0.030*"plan" + 0.030*"remain" + 0.029*"conversation" + 0.026*"chief" + 0.026*"street," + 0.025*"attention"'),
 (7,
  '0.037*"steps" + 0.036*"doubt" + 0.030*"done," + 0.029*"slightest" + 0.027*"makes" + 0.026*"meaning" + 0.020*"impressions" + 0.017*"actions" + 0.017*"fairly" + 0.016*"good"'),
 (13,
  '0.062*"nearly" + 0.050*"but," + 0.037*"hundred" + 0.025*"strong" + 0.024*"supposed" + 0.021*"years" + 0.019*"surface" + 0.018*"two" + 0.017*"one" + 0.016*"others,"'),
 (48,
  '0.074*"often" + 0.045*"family" + 0.041*"self" + 0.033*"lips" + 0.033*"could" + 0.030*"make" + 0.028*"enough" + 0.028*"uncle" + 0.026*"dare" + 0.026*"seemed"'),
 (69,
  '0.083*"come" + 0.081*"know" + 0.055*"said," + 0.051*"fear" + 0.049*"lost" + 0.027*"rest" + 0.027*"early" + 0.026*"lord" + 0.024*"would" + 0.024*"arose"'),
 (37,
  '0.068*"went" + 0.053*"state" + 0.041*"land" + 0.035*"beautiful" + 0.031*"native" + 0.026*"nature." + 0.025*"seems"

Представянето на запис в латентното пространство. Векторите са 100, но Gensim показва само най-значимите:

In [49]:
lda[corpus[0]]

[(8, 0.07315097),
 (25, 0.051196426),
 (38, 0.49518913),
 (41, 0.0514853),
 (45, 0.12152934),
 (68, 0.062701017),
 (78, 0.046702456),
 (86, 0.052045334)]

In [50]:
lda.get_document_topics(corpus[1], minimum_probability=0.00001)

[(0, 0.0014285714),
 (1, 0.0014285714),
 (2, 0.0014285714),
 (3, 0.0014285714),
 (4, 0.0014285714),
 (5, 0.0014285714),
 (6, 0.0014285714),
 (7, 0.0014285714),
 (8, 0.0014285714),
 (9, 0.0014285714),
 (10, 0.0014285714),
 (11, 0.0014285714),
 (12, 0.0014285714),
 (13, 0.0014285714),
 (14, 0.0014285714),
 (15, 0.0014285714),
 (16, 0.0014285714),
 (17, 0.0014285714),
 (18, 0.0014285714),
 (19, 0.0014285714),
 (20, 0.0014285714),
 (21, 0.0014285714),
 (22, 0.0014285714),
 (23, 0.0014285714),
 (24, 0.0014285714),
 (25, 0.0014285714),
 (26, 0.0014285714),
 (27, 0.0014285714),
 (28, 0.0014285714),
 (29, 0.0014285714),
 (30, 0.0014285714),
 (31, 0.0014285714),
 (32, 0.0014285714),
 (33, 0.0014285714),
 (34, 0.0014285714),
 (35, 0.0014285714),
 (36, 0.0014285714),
 (37, 0.0014285714),
 (38, 0.0014285714),
 (39, 0.0014285714),
 (40, 0.0014285714),
 (41, 0.0014285714),
 (42, 0.0014285714),
 (43, 0.0014285714),
 (44, 0.0014285714),
 (45, 0.20846553),
 (46, 0.0014285714),
 (47, 0.13822848),
 (48, 

In [51]:
print(len(corpus), len(train.author))

19579 19579


apply logistic regression, but first encode topics in dataframe

In [ ]:
latently = train.copy()
for t in range(100):
    latently[t]=0

print(latently[list(range(100))])

         0   1   2   3   4   5   6   7   8   9  ...  90  91  92  93  94  95  \
id                                              ...                           
id26305   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id17569   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id11008   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id27763   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id12958   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
...      ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..   
id17718   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id08973   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id05267   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id17513   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   
id00393   0   0   0   0   0   0   0   0   0   0 ... 

In [ ]:
data = []
for i, doc in enumerate(corpus):
    latently[list(range(100))].iloc[i] = [t[1] for t in lda.get_document_topics(doc, minimum_probability=0.00001)]
#     row = [train]
#     [t[1] for t in lda.get_document_topics(doc, minimum_probability=0.00001)]
#     data.append()

print(latently[list(range(100))])

/home/bob/.local/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [ ]:
AUTHOR_ENCODING = {'EAP': 0, 'MWS': 1, 'HPL': 2}
latently['encoded_author'] = [ AUTHOR_ENCODING[z] for z in train.author ]

In [ ]:
latently.shape

In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss

X_train, X_test, y_train, y_test = train_test_split(latently[list(range(100))], latently.encoded_author, random_state=42)

In [ ]:
logreg = LogisticRegression(C=0.01)

In [ ]:
%%time
logreg.fit(X_train, y_train)

In [ ]:
print("Test score: {:.2f}".format(logreg.score(X_test, y_test)))
prediction = logreg.predict_proba(X_test)
logloss = log_loss(y_test, prediction, labels=[0, 1, 2])
print('Log Loss score', logloss)

In [ ]:
print(prediction[:10])

In [99]:
print(X_test[:10])

             0         1         2         3         4         5         6   \
6148   0.001250  0.001250  0.126256  0.001250  0.001250  0.001250  0.001250   
4881   0.002500  0.002500  0.002500  0.002500  0.002500  0.002500  0.002500   
16114  0.000435  0.000435  0.000435  0.000435  0.000435  0.000435  0.056551   
738    0.000909  0.000909  0.000909  0.000909  0.000909  0.000909  0.000909   
13435  0.000909  0.000909  0.000909  0.000909  0.000909  0.000909  0.000909   
4706   0.000667  0.000667  0.000667  0.000667  0.000667  0.136325  0.000667   
11277  0.001250  0.001250  0.001250  0.001250  0.001250  0.001250  0.001250   
18884  0.002500  0.002500  0.002500  0.002500  0.002500  0.002500  0.252500   
8287   0.001111  0.001111  0.001111  0.001111  0.001111  0.001111  0.001111   
11993  0.005000  0.005000  0.005000  0.005000  0.005000  0.005000  0.005000   

             7         8         9     ...           90        91        92  \
6148   0.001250  0.001250  0.001250    ...     0.00

-----------------------------------------------

-----------------------------------------------

-----------------------------------------------

-----------------------------------------------

-----------------------------------------------

-----------------------------------------------

In [ ]:
fail here

In [ ]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, Dropout, Lambda, Concatenate
from keras.optimizers import RMSprop, Adam
from keras import regularizers, objectives, metrics
from keras.models import Model
from keras import backend as K

from IPython.display import display

# Откри приблизително същите параметри, но не успя да стигне напълно до същия резултат.

Ще използвам следния модел:

TfIdf + MultinomialNB, без стеминг на текста.

Mean validation score: -0.423 (std: 0.003)

Ще ползвам и следните параметри:

Parameters: {'features__stop_words': None, 'features__ngram_range': (1, 2), 'features__min_df': 2, 'features__max_df': 0.8, 'features__lowercase': False, 'features__analyzer': 'word', 'clf__alpha': 0.01}


Последна проверка на този модел за `LogLoss` и `Accuracy`

In [ ]:
from sklearn.naive_bayes import MultinomialNB

pipeline = Pipeline([
    ('features', TfidfVectorizer(ngram_range=(1, 2), min_df=2,
                                 max_df=0.8, lowercase=False)),
    ('clf', MultinomialNB(alpha=0.01))
])

print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3))
print(cross_val_score(pipeline, train.text, train.author, cv=3, n_jobs=3, 
                      scoring='neg_log_loss'))

# Трениране на модел и събмит

Първо да видим в какъв формат трябва да се подадат резултатите за тест

In [ ]:
sample_submission = pd.read_csv("data/spooky-authors/sample_submission.zip")
sample_submission.head()

In [ ]:
pipeline = pipeline.fit(train.text, train.author)

In [ ]:
print(pipeline.predict_proba(test[:10].text))

In [ ]:
test_predictions = pipeline.predict_proba(test.text)

In [ ]:
print(pipeline.classes_)

In [ ]:
submit_file = pd.DataFrame(test_predictions, columns=['EAP', 'MWS', 'HPL'], index=test.index)
submit_file.head(10)

In [ ]:
submit_file.to_csv("data/spooky-authors/submit_Tfidf_MNB_text.csv")

Очакванията за събмита са да имаме скор някъде около 0.41 - 0.42.

Може да е малко по-добър защото при крос-валидацията тренирахме на 13к и тествахме 6к.

Сега трейн сета е целия: 19.5к

![submit-result.png](attachment:submit-result.png)

In [ ]:
# Да хакнем ранкинга в кагъл?

print(test.text[:5].values)